### ISSUE TITLE
The issue about storage_path write permission in GSI

### ISSUE THREAD

**Issue by ittat** [capyloon/api-daemon#16]
As we discussed in the community, if someone flash a B2G GSI image with base on A13 to a device, which the device vendor version earlier than Android 10. The  path `/mnt/runtime/default/emulated/costaeres`  did not get write access. We need to adjust the appropriate path, maybe in `/data/local`.

**Comment by fabricedesre** [comment]
I agree, any safe path under `/data/local` should be fine.

**Comment by ittat** [comment]
On my devices, I moved the path to `/data/local/costaeres`. Let me know, do I need to open a PR for this issue?

**Comment by fabricedesre** [comment]
Yes please

**Comment by ittat** [comment]
fixed
